plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "app.golem.flutter"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    buildFeatures {
        // AGP 9 ships generated resource values disabled; the per-flavor
        // app_name labels below rely on them.
        resValues = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // The application ID is owned by the product flavors below.
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    // The three coexisting app identities. Launcher artwork lives in the
    // matching src/<flavor>/res source sets (generated by
    // tool/prepare_launcher.dart + flutter_launcher_icons); the manifest
    // resolves android:label from the per-flavor app_name resource.
    flavorDimensions += "environment"
    productFlavors {
        create("production") {
            dimension = "environment"
            applicationId = "app.golem"
            resValue("string", "app_name", "Golem")
        }
        create("qa") {
            dimension = "environment"
            applicationId = "app.golem.qa"
            resValue("string", "app_name", "Golem QA")
        }
        create("dev") {
            dimension = "environment"
            applicationId = "app.golem.dev"
            resValue("string", "app_name", "Golem Dev")
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
