plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    // The Kotlin package and resource namespace, deliberately shared by every
    // flavor; only the applicationId below varies. It is not an identity: the
    // production flavor happens to ship under the same string.
    namespace = "app.golem"
    compileSdk = flutter.compileSdkVersion
    // Pinned rather than inherited from flutter.ndkVersion. The Inferno build
    // hook compiles libinferno.so with whichever NDK it is handed, and Flutter
    // hands it the newest one installed on the machine — not this value. The
    // hook asserts the two agree (packages/inferno/hook/build.dart), which
    // only means anything if this side names an exact revision.
    ndkVersion = "29.0.14206865"

    packaging {
        jniLibs {
            // 16 KB devices need shared libraries stored uncompressed on a
            // page boundary. AGP 9 already packages them this way; saying so
            // stops a future default from reverting it silently. The real
            // guard reads the artifact: tool/check_android_packaging.dart.
            useLegacyPackaging = false
        }
    }

    buildFeatures {
        // AGP 9 ships generated resource values disabled; the per-flavor
        // app_name labels below rely on them.
        resValues = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // The application ID is owned by the product flavors below.
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName

        // Play has required API 36 or higher of new apps and updates since
        // 2026-08-31. targetSdk follows the Flutter SDK, so an older toolchain
        // would drop below the floor without anything saying so.
        require(flutter.targetSdkVersion >= 36) {
            "Play requires targetSdk 36 or higher; this Flutter SDK supplies " +
                "${flutter.targetSdkVersion}."
        }

        ndk {
            // Golem is arm64-only on Android: nothing below that tier can run
            // a multi-gigabyte model, and shipping an ABI whose Flutter engine
            // is absent makes Play offer the app to devices that install it
            // and crash. Plugin AARs carry prebuilt libraries for every ABI,
            // so the filter — not --target-platform — is what decides.
            //
            // Flutter's plugin writes armeabi-v7a/arm64-v8a/x86_64 here before
            // this block runs; clearing and re-setting in defaultConfig is the
            // override Flutter documents, and the only one it promises to
            // preserve:
            // docs.flutter.dev/release/breaking-changes/default-abi-filters-android
            abiFilters.clear()
            abiFilters.add("arm64-v8a")
        }
    }

    // The three coexisting app identities. Launcher artwork lives in the
    // matching src/<flavor>/res source sets (generated by
    // tool/prepare_launcher.dart + flutter_launcher_icons); the manifest
    // resolves android:label from the per-flavor app_name resource.
    flavorDimensions += "environment"
    productFlavors {
        create("production") {
            dimension = "environment"
            applicationId = "app.golem"
            resValue("string", "app_name", "Golem")
        }
        create("qa") {
            dimension = "environment"
            applicationId = "app.golem.qa"
            resValue("string", "app_name", "Golem QA")
        }
        create("dev") {
            dimension = "environment"
            applicationId = "app.golem.dev"
            resValue("string", "app_name", "Golem Dev")
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")

            // Both are AGP defaults today, and tool/check_android_packaging.dart
            // fails a release that arrives without their output — the R8
            // mapping and the per-ABI symbols Play needs to symbolicate
            // crashes. Stated so an AGP default flipping cannot drop
            // symbolication from the store artifact silently.
            isMinifyEnabled = true
            ndk {
                // SYMBOL_TABLE is AGP's default and what is stated here.
                // FULL adds DWARF and takes the bundle from 28 MB to 68 MB for
                // line numbers Play's crash reports do not need.
                debugSymbolLevel = "SYMBOL_TABLE"
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
